"""001_auth_tables

Revision ID: 452e8214a3fc
Revises: 
Create Date: 2026-09-07 02:58:35.639654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '452e8214a3fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('idade_anos', sa.Integer(), nullable=False),
    sa.Column('eh_menor_idade', sa.Boolean(), nullable=False),
    sa.Column('dados_responsavel', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('escola_tipo', sa.String(length=50), nullable=False),
    sa.Column('nome_escola', sa.String(length=200), nullable=True),
    sa.Column('serie_ano', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_role'), 'usuarios', ['role'], unique=False)
    op.create_table('sessoes_ativas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('ultimo_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_ativas_revogado'), 'sessoes_ativas', ['revogado'], unique=False)
    op.create_index(op.f('ix_sessoes_ativas_session_token'), 'sessoes_ativas', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessoes_ativas_usuario_id'), 'sessoes_ativas', ['usuario_id'], unique=False)
    op.create_table('tokens_recuperacao_senha',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilizado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_recuperacao_senha_token_hash'), 'tokens_recuperacao_senha', ['token_hash'], unique=True)
    op.create_index(op.f('ix_tokens_recuperacao_senha_usuario_id'), 'tokens_recuperacao_senha', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_recuperacao_senha_usuario_id'), table_name='tokens_recuperacao_senha')
    op.drop_index(op.f('ix_tokens_recuperacao_senha_token_hash'), table_name='tokens_recuperacao_senha')
    op.drop_table('tokens_recuperacao_senha')
    op.drop_index(op.f('ix_sessoes_ativas_usuario_id'), table_name='sessoes_ativas')
    op.drop_index(op.f('ix_sessoes_ativas_session_token'), table_name='sessoes_ativas')
    op.drop_index(op.f('ix_sessoes_ativas_revogado'), table_name='sessoes_ativas')
    op.drop_table('sessoes_ativas')
    op.drop_index(op.f('ix_usuarios_role'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
