"""004_exercise_tables

Revision ID: de042328f643
Revises: 0df7b4f4b350
Create Date: 2026-09-09 03:37:01.700716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de042328f643'
down_revision: Union[str, None] = '0df7b4f4b350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provas_cat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('disciplina_id', sa.UUID(), nullable=False),
    sa.Column('tipo_prova', sa.String(length=30), nullable=False),
    sa.Column('theta_geral', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('erro_padrao_se', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('scores_grandes_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_itens_aplicados', sa.Integer(), nullable=False),
    sa.Column('itens_respondidos_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('respostas_detalhadas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provas_cat_usuario_disciplina', 'provas_cat', ['usuario_id', 'disciplina_id'], unique=False)
    op.create_table('itens_exercicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capitulo_id', sa.UUID(), nullable=False),
    sa.Column('tipo_origem', sa.String(length=30), nullable=False),
    sa.Column('tipo_item', sa.String(length=30), nullable=False),
    sa.Column('item_matriz_id', sa.UUID(), nullable=True),
    sa.Column('enunciado_katex', sa.Text(), nullable=False),
    sa.Column('alternativas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resposta_correta', sa.String(length=50), nullable=False),
    sa.Column('resolucao_passo_a_passo', sa.Text(), nullable=False),
    sa.Column('parametro_a', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('parametro_b', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('parametro_c', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('metadados_sympy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validado_sympy', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_matriz_id'], ['itens_exercicios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_itens_capitulo', 'itens_exercicios', ['capitulo_id', 'ativo'], unique=False)
    op.create_index('idx_itens_matriz', 'itens_exercicios', ['item_matriz_id'], unique=False)
    op.create_table('caixa_reforco',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('capitulo_id', sa.UUID(), nullable=False),
    sa.Column('total_erros', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arquivado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['itens_exercicios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_caixa_reforco_capitulo', 'caixa_reforco', ['usuario_id', 'capitulo_id'], unique=False)
    op.create_index('idx_caixa_reforco_pendente', 'caixa_reforco', ['usuario_id', 'status'], unique=False)
    op.create_table('tentativas_exercicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('capitulo_id', sa.UUID(), nullable=False),
    sa.Column('tentativa_numero', sa.Integer(), nullable=False),
    sa.Column('resposta_enviada', sa.String(length=150), nullable=False),
    sa.Column('acertou', sa.Boolean(), nullable=False),
    sa.Column('pontuacao_obtida', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('usou_dica_ia', sa.Boolean(), nullable=False),
    sa.Column('tempo_resposta_segundos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_id'], ['capitulos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['itens_exercicios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tentativas_item', 'tentativas_exercicios', ['item_id'], unique=False)
    op.create_index('idx_tentativas_usuario_capitulo', 'tentativas_exercicios', ['usuario_id', 'capitulo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tentativas_usuario_capitulo', table_name='tentativas_exercicios')
    op.drop_index('idx_tentativas_item', table_name='tentativas_exercicios')
    op.drop_table('tentativas_exercicios')
    op.drop_index('idx_caixa_reforco_pendente', table_name='caixa_reforco')
    op.drop_index('idx_caixa_reforco_capitulo', table_name='caixa_reforco')
    op.drop_table('caixa_reforco')
    op.drop_index('idx_itens_matriz', table_name='itens_exercicios')
    op.drop_index('idx_itens_capitulo', table_name='itens_exercicios')
    op.drop_table('itens_exercicios')
    op.drop_index('idx_provas_cat_usuario_disciplina', table_name='provas_cat')
    op.drop_table('provas_cat')
    # ### end Alembic commands ###
